[colors.bright]
black = '#928374'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#8ec07c'
white = '#ebdbb2'

[colors.normal]
black = '#282828'
red = '#cc241d'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#689d6a'
white = '#a89984'

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[font]
size = 14

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window]
opacity = 0.78
